---
title: "Suhaani-Animint-Gallery"
author: "Suhaani Agarwal"
date: "2025-03-07"
output: html_document
---

```{r, echo=FALSE}
# Install required packages if not already installed
if (!require(kableExtra)) install.packages("kableExtra")
if (!require(rmarkdown)) install.packages("rmarkdown")
if (!require(animint2)) install.packages("animint2")
if (!require(knitr)) install.packages("knitr")
if (!require(DT)) install.packages("DT")

library(kableExtra)
library(rmarkdown)
library(animint2)
library(knitr)
library(DT)

# Read the metadata
if (!file.exists("meta.csv")) {
  stop("The file 'meta.csv' does not exist. Please create it.")
}
dt <- read.csv('meta.csv')

# Generate image links from the local 'images' folder
no_of_ani <- dim(dt)[1]
image_links <- character(no_of_ani)  # Use character instead of numeric
for (i in 1:no_of_ani) {
  if (!is.na(dt$image_file[i]) && dt$image_file[i] != "") {
    image_links[i] <- sprintf("images/%s", dt$image_file[i])
  } else {
    image_links[i] <- "images/placeholder.png"  # Use a placeholder image if no image is specified
  }
}

# Extract creator and visualization title
Creator <- strsplit(dt$viz_owner_repo, split = "/")
CreatorName <- numeric(length(Creator))
viz.title <- numeric(length(Creator))
for (i in 1:length(Creator)) {
  CreatorName[i] <- Creator[[i]][1]
  viz.title[i] <- Creator[[i]][2]
}

# Generate visualization links
Visualization_Link <- sprintf("%s%s", viz.title, ".viz")

# Generate source links
Source <- paste0("<a href=", dt$source, ">", dt$title, "</a>")

# Generate GitHub Pages links
viz.link <- sprintf("https://%s.github.io/%s/%s/index.html", CreatorName, "r", dt$folder)

# Generate GitHub repository links
gh_page_repo_link <- sprintf("https://github.com/%s/tree/main/%s", dt$viz_owner_repo, dt$folder)
gh_page_repo <- paste0("<a href=", gh_page_repo_link, ">", dt$commit.POSIXct, "</a>")

# Generate visualization links with HTML
Visualization_Link <- paste0("<a href=", viz.link, ">", Visualization_Link, "</a>")

# Combine data into a table
full_data <- cbind(Image = "", Visualization_Link, dt, Source, gh_page_repo, CreatorName)
full_data <- full_data[, c(1, 2, 8, 9)]

# Create and style the table
kable(full_data, format = "html", escape = FALSE) %>%
  kable_styling(full_width = FALSE) %>%
  column_spec(1, image = image_links)